name: road_to_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  provider: ^4.0.4
  firebase_auth: ^0.15.5+2
  firebase_core: ^0.4.4+3
  carousel_pro: ^1.0.0
  firebase_database: ^3.1.3
  cloud_firestore: ^0.13.4+2
  google_sign_in: 
  flutter_spinkit: ^4.1.2
  stripe_payment: ^1.0.6
  flutter_rave: ^0.0.5



  cupertino_icons: ^0.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
   
